# Generated by Django 4.2.6 on 2023-10-07 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardlist',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='boardlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
