# Generated by Django 4.2.6 on 2023-10-07 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_list', '0002_boardlist_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardlist',
            old_name='user',
            new_name='owner',
        ),
    ]
