# Generated by Django 4.2.6 on 2023-10-07 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_remove_board_boardlist'),
        ('board_list', '0003_rename_user_boardlist_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardlist',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boardlist', to='board.board'),
        ),
    ]
