# Generated by Django 4.2.6 on 2023-10-07 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_list', '0004_alter_boardlist_board'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardlist',
            name='board',
        ),
    ]
