# Generated by Django 4.2.6 on 2023-10-08 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_remove_board_boardlist'),
        ('board_list', '0005_remove_boardlist_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardlist',
            name='board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='boardList', to='board.board'),
            preserve_default=False,
        ),
    ]
