# Generated by Django 4.2.6 on 2023-10-08 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('board', '0015_remove_board_boardlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('colours', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('boardlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card', to='board.board')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='card', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
