# Generated by Django 4.2.6 on 2023-10-08 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board_list', '0008_alter_boardlist_board'),
        ('cards', '0002_rename_cards_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='boardlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card', to='board_list.boardlist'),
        ),
    ]
