# Generated by Django 4.2.6 on 2023-10-11 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board_list', '0010_alter_boardlist_board'),
        ('cards', '0003_alter_card_boardlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='boardlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='board_list.boardlist'),
        ),
        migrations.AlterField(
            model_name='card',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cards', to=settings.AUTH_USER_MODEL),
        ),
    ]
