# Generated by Django 4.2.6 on 2023-10-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_alter_card_boardlist_alter_card_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='colours',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
