# Generated by Django 4.2.6 on 2023-10-07 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_remove_board_boardlist_board_boardlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='boardlist',
        ),
    ]
