# Generated by Django 4.2.6 on 2023-10-08 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_board_boardlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='boardlist',
        ),
    ]
