# Generated by Django 4.2.6 on 2023-10-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_list', '0006_boardlist_board'),
        ('board', '0012_remove_board_boardlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='boardlist',
            field=models.ManyToManyField(blank=True, related_name='boardList', to='board_list.boardlist'),
        ),
    ]
