# Generated by Django 4.2.6 on 2023-10-08 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board_list', '0006_boardlist_board'),
        ('board', '0013_board_boardlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='boardlist',
        ),
        migrations.AddField(
            model_name='board',
            name='boardlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boardList', to='board_list.boardlist'),
        ),
    ]
