# Generated by Django 4.2.6 on 2023-10-12 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0015_remove_board_boardlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='collaborators',
        ),
        migrations.AddField(
            model_name='board',
            name='collaborators',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaborators_board', to=settings.AUTH_USER_MODEL),
        ),
    ]
