# Generated by Django 4.2.6 on 2023-10-12 18:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0016_remove_board_collaborators_board_collaborators'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='collaborators',
        ),
        migrations.AddField(
            model_name='board',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='Collaborators_board', to=settings.AUTH_USER_MODEL),
        ),
    ]
