# Generated by Django 4.2.6 on 2023-10-12 20:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0017_remove_board_collaborators_board_collaborators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collaborators', to=settings.AUTH_USER_MODEL),
        ),
    ]
