# Generated by Django 4.2.6 on 2023-10-12 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0019_remove_board_collaborators_board_collaborators'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='collaborators',
        ),
    ]
